services:
  web:
    image: talen8/flec-web:latest
    container_name: flec_web
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:8080/api/v1
    ports:
      - "8082:80"
